export default currentAgents = [
    { name: 'Astra', img: './src/images/' },
    { name: 'Breach', img: './src/images/' },
    { name: 'Brimstone', img: './src/images/' },
    { name: 'Chamber', img: './src/images/' },
    { name: 'Clove', img: './src/images/' },
    { name: 'Cypher', img: './src/images/' },
    { name: 'Deadlock', img: './src/images/' },
    { name: 'Fade', img: './src/images/' },
    { name: 'Gekko', img: './src/images/' },
    { name: 'Harbor', img: './src/images/' },
    { name: 'Iso', img: './src/images/' },
    { name: 'Jett', img: './src/images/' },
    { name: 'KAY/O', img: './src/images/' },
    { name: 'Killjoy', img: './src/images/' },
    { name: 'Neon', img: './src/images/' },
    { name: 'Omen', img: './src/images/' },
    { name: 'Phoenix', img: './src/images/' },
    { name: 'Raze', img: './src/images/' },
    { name: 'Reyna', img: './src/images/' },
    { name: 'Sage', img: './src/images/' },
    { name: 'Skye', img: './src/images/' },
    { name: 'Sova', img: './src/images/' },
    { name: 'Viper', img: './src/images/' },
    { name: 'Yoru', img: './src/images/' },
]
